### ISSUE TITLE
Please update.

### ISSUE THREAD

**Issue by OfficialUseless** [devadvance/rootcloak#195]
this is not working please update. or someone please help me.

**Comment by hikaritenchi** [comment]
This project has largely been abandoned and doesn't support hiding root from most apps nowadays. I encourage you to look for other ways of hiding root through a Magisk module or something similar. I personally haven't been rooted for many years.

**Comment by OfficialUseless** [comment]
> This project has largely been abandoned and doesn't support hiding root from most apps nowadays. I encourage you to look for other ways of hiding root through a Magisk module or something similar. I personally haven't been rooted for many years.

thank you for your advice. but i have no luck. can't find anythin like this one..this is working fine. but not working for all apps...😪

**Comment by hikaritenchi** [comment]
The apps that it doesn't work with are probably using the more advanced root detection techniques, so this one won't work either way. RootCloak uses a very specific hiding technique and there are no plans to add any additional ones, because there are other root hiding techniques that are better suited for other detection techniques.
