### ISSUE TITLE
native hooks app picker should only setprop for changes, not all apps

### ISSUE THREAD

**Issue by Phoenix09** [devadvance/rootcloak#84]
at the moment it runs setprop and force stop for all apps resulting in rootcloak being unresponsive for around two minutes on my Galaxy S6
this would be a bigger issue on low spec devices

**Comment by AngryManjuu** [comment]
It freezes my device for a minute and force reboots it on the Xperia C3

**Comment by pylerSM** [comment]
Okey, will be fixed

**Comment by Phoenix09** [comment]
as SU is being called on the main thread it's blocking until it completes
I would change it to run all commands in an interactive shell (which would be faster than running each command in its own shell) and make it asynchronous
see these links:
https://github.com/Chainfire/libsuperuser/blob/master/libsuperuser_example/src/eu/chainfire/libsuperuser_example/InteractiveActivity.java
http://su.chainfire.eu/#when-async

**Comment by pylerSM** [comment]
Good idea.

**Comment by pylerSM** [comment]
It will be part of https://github.com/devadvance/rootcloak/pull/90

**Comment by devadvance** [comment]
Merged.

**Comment by Phoenix09** [comment]
using 20160731_2 it's completely broken
I enabled some apps, none of the ones in the SuperSU log are what I enabled, there's 133 setprop calls in the log
I enabled only 3 apps and have about 300 user apps on my phone

**Comment by pylerSM** [comment]
"133 setprop calls " - this is my part so I can answer it.

When you uncheck app in native root detection, we need to disable native hooking for this app.
so we need to setprop wrap.packagename ''' -> to disable our hacking library to be loaded with app together :dancer: This only happens when you change apps in Native root detection more times during one device boot. After you reboot device, we need to setprop all apps again, but in this case, we dont need to setprop unchecked apps to '' because reboot resetted (deleted) all props we set, so we only set wrap props only for "enabled apps".

No I am gonna test 20160731_2, I know 20160731_1 was fine.

Edit: I tested and it is fine for me. Can you reinstall it fully? 

I disabled force stop when you uncheck some apps, since it may force close many user apps which run currently. Patch:
https://github.com/devadvance/rootcloak/pull/101

**Comment by Phoenix09** [comment]
uninstalled, rebooted, reinstalled, rebooted, same problem

**Comment by Phoenix09** [comment]
I enabled it for Root Inspector only
log from SuperSU here: https://mega.nz/#!ot4RFSyK!uzaFTIVpcqExVtSKsvOS6qZRBQ_mzBZNFCNYg9GHpQE

**Comment by pylerSM** [comment]
On my nexus 7 works.

**Comment by Phoenix09** [comment]
not working on my Nexus 7 (2013) with CM13

**Comment by NHellFire** [comment]
> When you uncheck app in native root detection, we need to disable native hooking for this app.
so we need to setprop wrap.packagename ''' -> to disable our hacking library to be loaded with app together
Yes, but if it wasn't enabled before, it shouldn't process it. It should compare old settings to new and only call setprop for the ones that were changed.

**Comment by pylerSM** [comment]
Feel free to make it better. setprop wrap.packagename '' does nothing bad anyway.

**Comment by NHellFire** [comment]
No, it's just slow running setprop 200 times in a row.
